name: Build and Deploy to VPS

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: create env file
        run: |
          touch .env
          echo "REACT_APP_API_URI=http://api.Text Corpus.fabricadestartup.com.br" >> .env
          cat .env
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: 18
#      - run: rm yarn.lock
      - run: yarn
      - run: yarn build
        env:
          CI: false
      - name: Compress action step
        uses: a7ul/tar-action@v1.1.0
        id: compress
        with:
          command: c
          cwd: ./
          files: |
            ./build
          outPath: painel.tar.gz
      - name: Copy painel via ssh
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASS }}
          source: "./painel.tar.gz"
          target: "/home/diogo"
      - name: Deploy files in VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASS }}          
          script: |
            tar -zxpf painel.tar.gz
            rm painel.tar.gz
            cp -Rf build/* /Text Corpus/painel/release
            rm -Rf build
